### PR TITLE
Fix update_axes to respect selector duration instead of hardcoded 1000ms

### LINKED ISSUE #276: update_axes duration is always 1000
but it should be the same as the corresponding duration option (whatever selector is updated).

### PR DESCRIPTION
**Pull request by ANAMASGARD**
Fixes #276

## Problem

The `update_axes()` function in the JavaScript renderer was using a hardcoded transition duration of 1000ms, regardless of what duration was set for the selector triggering the axis update.

This meant that when a user specified `duration=list(year=2000)` for a year selector, clicking to change years would cause:
- The data points to transition over 2000ms (correct)
- The axes to transition over 1000ms (incorrect - looks janky)

## Testing

Added `test-renderer3-update-axes-duration.R` which:
- Creates a visualization with `duration=list(year=2000)` 
- Verifies that axis transitions take 2000ms by checking position at 1200ms
- With the bug: transition completes in 1000ms, test fails 
- With the fix: transition takes 2000ms, test passes 

This failing test committed first, then the fix in a upcoming commits .

### CODE REVIEW

**Review by tdhock — CHANGES_REQUESTED** [review]
please fix test failures before asking for review

File: inst/htmljs/animint.js [hunk 1]
```diff
@@ -2012,7 +2012,9 @@ var animint = function (to_select, json_file) {
     var xyaxis_sel = element.select("#plot_"+p_name).select("."+axes+"axis_"+panel_i);
     // Fix for issue #276: use selector's duration instead of hardcoded 1000ms
     var milliseconds = 0; // default: no transition when no duration specified
-    if(Selectors.hasOwnProperty(v_name) && Selectors[v_name].duration){
+    if(Selectors.hasOwnProperty(v_name) && 
+       Selectors[v_name].hasOwnProperty("duration") &&
+       typeof Selectors[v_name].duration === "number"){
```
Comment (tdhock) [inline inst/htmljs/animint.js]: this check is un-necessary because duration is always a number

**Comment by ANAMASGARD** [comment]
Sir @tdhock  Can you please review this PR now and give your feedback is there anything I need to change .

**Review by tdhock — CHANGES_REQUESTED** [review]

File: tests/testthat/test-renderer3-update-axes-duration.R [hunk 2]
```diff
@@ -31,8 +31,7 @@ updated_tick_diff_y <- getTickDiff(y_axis_node_updated, axis="y")
 
 test_that("update_axes uses selector duration for transitions", {
   # Verify ticks changed (confirms update_axes was called with correct duration)
-  expect_false(identical(updated_tick_diff_x, original_tick_diff_x),
-               info="X-axis ticks should change when selector changes")
-  expect_false(identical(updated_tick_diff_y, original_tick_diff_y),
-               info="Y-axis ticks should change when selector changes")
+  # Use numeric comparison - tick differences should change when selector changes
+  expect_gt(abs(updated_tick_diff_x[2] - original_tick_diff_x[2]), 0.01)
```
Comment (tdhock) [inline tests/testthat/test-renderer3-update-axes-duration.R]: why 2 and 0.01? please avoid magic numbers

**Review by tdhock — CHANGES_REQUESTED** [review]

File: tests/testthat/test-renderer3-update-axes-duration.R [hunk 3]
```diff
@@ -31,7 +31,9 @@ updated_tick_diff_y <- getTickDiff(y_axis_node_updated, axis="y")
 
 test_that("update_axes uses selector duration for transitions", {
   # Verify ticks changed (confirms update_axes was called with correct duration)
-  # Use numeric comparison - tick differences should change when selector changes
-  expect_gt(abs(updated_tick_diff_x - original_tick_diff_x), 0.01)
-  expect_gt(abs(updated_tick_diff_y - original_tick_diff_y), 0.01)
+  # Using same pattern as test-renderer3-update-axes.R
+  expect_true(unequal(updated_tick_diff_x, original_tick_diff_x, tolerance=0.01),
```
Comment (tdhock) [inline tests/testthat/test-renderer3-update-axes-duration.R]: this is frustrating for me.
I already told you to avoid expect true and false, and now you put it back? 
please remove 0.01 or explain why it is relevant and necessary.

**Review by tdhock — CHANGES_REQUESTED** [review]

**Comment by ANAMASGARD** [comment]
I sincerely apologize Sir you are absolutely right I should have followed your previous feedback 
THE THINGS I HAVE CHANGED THIS TIME 

- Replaced expect_true with expect_gt - a more specific assertion as you requested
 - Removed the 0.01 tolerance - we now simply check that the difference is greater than 0
 - Added a comment explaining why tick spacing changes (different cyl subsets have different mpg/disp ranges)
 - The test now directly asserts that the tick spacing changed (difference > 0) without any magic numbers or expect_true/expect_false.

**Review by tdhock — CHANGES_REQUESTED** [review]
